---
- name: Check if guest agent is availible
  ansible.builtin.stat:
    path: "/dev/virtio-ports"
  register: qemu_guest_agent_device
  when: qemu_guest_agent_state == "detect"

- name: Ensure qemu-guest-agent is installed
  ansible.builtin.apt:
    cache_valid_time: 900
    name: "qemu-guest-agent"
    state: "{{ 'latest' if qemu_guest_agent_state == 'latest' else 'present' }}"
  become: true
  when: >-
    qemu_guest_agent_state == "present"
    or qemu_guest_agent_state == "latest"
    or (qemu_guest_agent_device.stat.exists is defined
    and qemu_guest_agent_device.stat.exists is true)

- name: Ensure qemu-guest-agent is started and enabled
  ansible.builtin.service:
    name: "qemu-guest-agent"
    state: "started"
    enabled: true
  become: true
  when: >-
    qemu_guest_agent_state == "present"
    or qemu_guest_agent_state == "latest"
    or (qemu_guest_agent_device.stat.exists is defined
    and qemu_guest_agent_device.stat.exists is true)

- name: Ensure qemu-guest-agent is not installed
  ansible.builtin.package:
    name: "qemu-guest-agent"
    state: "absent"
  become: true
  when: >-
    qemu_guest_agent_state == "absent" or
    (qemu_guest_agent_device.stat.exists is defined
    and qemu_guest_agent_device.stat.exists is false)
